version: '3'

services:
  dummypage:
    build: .
    image: dummypage:build
    working_dir: /code
    command: uvicorn app:app --host 0.0.0.0 --port 5000 --http httptools --loop uvloop --timeout-keep-alive 0
    container_name: dummypage
    restart: always
    networks:
      - web
    volumes:
      - /opt/cfgs:/site/cfgs:ro
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.routers.dummypage.rule=Host(`xenking.pro`)
      - traefik.http.routers.dummypage.tls=true
      - traefik.http.routers.dummypage.service=dummypage
      - traefik.http.routers.dummypage.entrypoints=https
     # - traefik.http.routers.dummypage.tls.certresolver=main
     # - traefik.http.routers.dummypage.tls.domains[0].main=*.xenking.pro
     # - traefik.http.routers.dummypage.tls.domains[0].sans=*.xenking.pro
      - traefik.http.services.dummypage.loadbalancer.server.port=5000
      - traefik.http.services.dummypage.loadbalancer.server.scheme=http
networks:
  web:
    external: true
